export interface PlanetStats {
  mass: string;
  gravity: string;
  avgTemp: string;
  atmosphere: string;
  moons: number;
  dayLength: string;
  yearLength: string;
}

export interface PlanetData {
  name: string;
  radius: number; // km
  distanceFromSun: number; // AU
  displayDistance: number; // compressed scene units
  displayRadius: number; // compressed scene units
  color: string;
  emissiveColor?: string;
  orbitalPeriod: number; // Earth days
  rotationPeriod: number; // hours
  tilt: number; // axial tilt degrees
  facts: string[];
  stats: PlanetStats;
  description: string;
  hasRings?: boolean;
  ringColor?: string;
}

// Square-root scaling keeps gas giants visibly larger while not drowning rocky planets
function scaleRadius(kmRadius: number): number {
  const base = Math.sqrt(kmRadius / 6371); // normalized to Earth = 1
  return Math.max(base * 0.7, 0.25); // Earth ~0.7, Jupiter ~2.3, min 0.25
}

const BASE_DISTANCE = 10;
const DISTANCE_STEP = 7;

export const planets: PlanetData[] = [
  {
    name: "Mercury",
    radius: 2439.7,
    distanceFromSun: 0.387,
    displayDistance: BASE_DISTANCE,
    displayRadius: scaleRadius(2439.7),
    color: "#8c7e6d",
    orbitalPeriod: 88,
    rotationPeriod: 1407.6,
    tilt: 0.034,
    facts: [
      "Mercury is the smallest planet in our solar system — only slightly larger than Earth's Moon.",
      "A day on Mercury (sunrise to sunrise) lasts 176 Earth days, even though it orbits the Sun in just 88 days.",
      "Despite being closest to the Sun, Mercury is not the hottest planet — Venus is, thanks to its greenhouse effect.",
      "Mercury has no atmosphere to retain heat, so temperatures swing from 430°C during the day to -180°C at night.",
      "The Caloris Basin on Mercury is one of the largest impact craters in the solar system, about 1,550 km across.",
    ],
    stats: {
      mass: "3.30 × 10²³ kg",
      gravity: "3.7 m/s²",
      avgTemp: "167°C",
      atmosphere: "Virtually none",
      moons: 0,
      dayLength: "4,222.6 hours",
      yearLength: "88 days",
    },
    description:
      "Mercury is a small, cratered world baking in the Sun's glare. It whips around its orbit faster than any other planet, completing a year in just 88 Earth days. Its surface resembles our Moon — ancient, battered, and airless.",
  },
  {
    name: "Venus",
    radius: 6051.8,
    distanceFromSun: 0.723,
    displayDistance: BASE_DISTANCE + DISTANCE_STEP,
    displayRadius: scaleRadius(6051.8),
    color: "#e8cda0",
    orbitalPeriod: 224.7,
    rotationPeriod: -5832.5,
    tilt: 177.4,
    facts: [
      "Venus spins backward compared to most planets — the Sun rises in the west and sets in the east.",
      "Its thick atmosphere traps heat so effectively that Venus is hotter than Mercury, reaching 465°C.",
      "A day on Venus (243 Earth days) is longer than its year (225 Earth days).",
      "Venus is often called Earth's 'twin' because of their similar size, but conditions are radically different.",
      "The atmospheric pressure on Venus's surface is about 90 times that of Earth — like being 900 meters underwater.",
    ],
    stats: {
      mass: "4.87 × 10²⁴ kg",
      gravity: "8.87 m/s²",
      avgTemp: "464°C",
      atmosphere: "96.5% CO₂, 3.5% N₂",
      moons: 0,
      dayLength: "2,802 hours",
      yearLength: "225 days",
    },
    description:
      "Venus is Earth's toxic twin — similar in size but wrapped in a suffocating blanket of carbon dioxide clouds. Its runaway greenhouse effect makes it the hottest planet in the solar system, with crushing surface pressure and sulfuric acid rain.",
  },
  {
    name: "Earth",
    radius: 6371,
    distanceFromSun: 1.0,
    displayDistance: BASE_DISTANCE + DISTANCE_STEP * 2,
    displayRadius: scaleRadius(6371),
    color: "#4a90d9",
    orbitalPeriod: 365.25,
    rotationPeriod: 23.93,
    tilt: 23.44,
    facts: [
      "Earth is the only known planet to harbor life — and 71% of its surface is covered in water.",
      "Our planet's magnetic field, generated by its molten iron core, shields us from harmful solar radiation.",
      "Earth is the densest planet in the solar system at 5.51 g/cm³.",
      "The atmosphere is 78% nitrogen and 21% oxygen — a composition unique in the solar system.",
      "Plate tectonics constantly reshape Earth's surface, a process not observed on any other planet.",
    ],
    stats: {
      mass: "5.97 × 10²⁴ kg",
      gravity: "9.81 m/s²",
      avgTemp: "15°C",
      atmosphere: "78% N₂, 21% O₂",
      moons: 1,
      dayLength: "24 hours",
      yearLength: "365.25 days",
    },
    description:
      "Earth is the third rock from the Sun and the only world known to support life. Its liquid water, protective atmosphere, and magnetic field create a uniquely hospitable environment in an otherwise harsh solar system.",
  },
  {
    name: "Mars",
    radius: 3389.5,
    distanceFromSun: 1.524,
    displayDistance: BASE_DISTANCE + DISTANCE_STEP * 3,
    displayRadius: scaleRadius(3389.5),
    color: "#c1440e",
    orbitalPeriod: 687,
    rotationPeriod: 24.62,
    tilt: 25.19,
    facts: [
      "Olympus Mons on Mars is the tallest volcano in the solar system — nearly 3 times the height of Everest.",
      "Mars has seasons like Earth because of its similar axial tilt (25.19° vs Earth's 23.44°).",
      "Valles Marineris is a canyon system stretching 4,000 km — roughly the width of the United States.",
      "Mars's thin atmosphere is 95% carbon dioxide with an atmospheric pressure less than 1% of Earth's.",
      "Evidence suggests liquid water once flowed on Mars, and subsurface ice still exists today.",
    ],
    stats: {
      mass: "6.42 × 10²³ kg",
      gravity: "3.72 m/s²",
      avgTemp: "-65°C",
      atmosphere: "95% CO₂, 2.7% N₂",
      moons: 2,
      dayLength: "24.6 hours",
      yearLength: "687 days",
    },
    description:
      "Mars, the Red Planet, captivates us as the most Earth-like world in the solar system. Its rusty iron-oxide surface, massive volcanoes, and deep canyons tell the story of a planet that was once warmer and wetter.",
  },
  {
    name: "Jupiter",
    radius: 69911,
    distanceFromSun: 5.203,
    displayDistance: BASE_DISTANCE + DISTANCE_STEP * 5,
    displayRadius: scaleRadius(69911),
    color: "#c88b3a",
    orbitalPeriod: 4331,
    rotationPeriod: 9.93,
    tilt: 3.13,
    facts: [
      "Jupiter is so massive that it contains more than twice the mass of all other planets combined.",
      "The Great Red Spot is a storm larger than Earth that has been raging for at least 350 years.",
      "Jupiter has at least 95 known moons, including the four large Galilean moons discovered in 1610.",
      "Jupiter's powerful magnetic field is 20,000 times stronger than Earth's.",
      "If Jupiter had been about 80 times more massive, it would have become a star instead of a planet.",
    ],
    stats: {
      mass: "1.90 × 10²⁷ kg",
      gravity: "24.79 m/s²",
      avgTemp: "-110°C",
      atmosphere: "90% H₂, 10% He",
      moons: 95,
      dayLength: "9.9 hours",
      yearLength: "11.86 years",
    },
    description:
      "Jupiter is the king of planets — a gas giant so enormous that over 1,300 Earths could fit inside it. Its swirling bands of ammonia clouds and iconic Great Red Spot make it one of the most visually striking objects in the solar system.",
  },
  {
    name: "Saturn",
    radius: 58232,
    distanceFromSun: 9.537,
    displayDistance: BASE_DISTANCE + DISTANCE_STEP * 7,
    displayRadius: scaleRadius(58232),
    color: "#d4a94b",
    emissiveColor: "#2a2010",
    orbitalPeriod: 10747,
    rotationPeriod: 10.7,
    tilt: 26.73,
    hasRings: true,
    ringColor: "#a08050",
    facts: [
      "Saturn's rings are made of billions of chunks of ice and rock, ranging from tiny grains to house-sized boulders.",
      "Saturn is the least dense planet — it would float if you could find a bathtub big enough.",
      "Winds on Saturn can reach up to 1,800 km/h, among the fastest in the solar system.",
      "Saturn's moon Titan is the only moon with a thick atmosphere and liquid lakes on its surface (of methane and ethane).",
      "The ring system spans up to 282,000 km from the planet but is only about 10 meters thick in most places.",
    ],
    stats: {
      mass: "5.68 × 10²⁶ kg",
      gravity: "10.44 m/s²",
      avgTemp: "-140°C",
      atmosphere: "96% H₂, 3% He",
      moons: 146,
      dayLength: "10.7 hours",
      yearLength: "29.46 years",
    },
    description:
      "Saturn is the jewel of the solar system, instantly recognizable by its spectacular ring system. This gas giant is nearly as large as Jupiter but far less dense — it's the only planet that would float in water.",
  },
  {
    name: "Uranus",
    radius: 25362,
    distanceFromSun: 19.19,
    displayDistance: BASE_DISTANCE + DISTANCE_STEP * 9,
    displayRadius: scaleRadius(25362),
    color: "#7ec8e3",
    orbitalPeriod: 30589,
    rotationPeriod: -17.24,
    tilt: 97.77,
    hasRings: true,
    ringColor: "#556677",
    facts: [
      "Uranus rotates on its side with an axial tilt of 98° — likely the result of a massive ancient collision.",
      "It was the first planet discovered with a telescope, found by William Herschel in 1781.",
      "Uranus has 13 known rings, which are dark and narrow compared to Saturn's bright, wide rings.",
      "Methane in the atmosphere absorbs red light, giving Uranus its distinctive blue-green color.",
      "Wind speeds on Uranus can reach 900 km/h, and temperatures drop to -224°C in its atmosphere.",
    ],
    stats: {
      mass: "8.68 × 10²⁵ kg",
      gravity: "8.87 m/s²",
      avgTemp: "-195°C",
      atmosphere: "83% H₂, 15% He, 2% CH₄",
      moons: 28,
      dayLength: "17.2 hours",
      yearLength: "84 years",
    },
    description:
      "Uranus is the oddball of the solar system — an ice giant rolling around the Sun on its side. Its pale blue-green hue comes from methane ice in its atmosphere, and it holds the record for the coldest planetary atmosphere ever measured.",
  },
  {
    name: "Neptune",
    radius: 24622,
    distanceFromSun: 30.07,
    displayDistance: BASE_DISTANCE + DISTANCE_STEP * 11,
    displayRadius: scaleRadius(24622),
    color: "#3454b4",
    orbitalPeriod: 59800,
    rotationPeriod: 16.11,
    tilt: 28.32,
    facts: [
      "Neptune has the strongest sustained winds of any planet, reaching speeds of 2,100 km/h.",
      "It was the first planet located through mathematical prediction rather than direct observation (1846).",
      "Neptune's moon Triton orbits in the opposite direction of the planet's rotation — likely a captured Kuiper Belt object.",
      "One year on Neptune lasts 165 Earth years; it completed its first full orbit since discovery in 2011.",
      "Despite receiving very little sunlight, Neptune radiates more than twice as much energy as it receives from the Sun.",
    ],
    stats: {
      mass: "1.02 × 10²⁶ kg",
      gravity: "11.15 m/s²",
      avgTemp: "-200°C",
      atmosphere: "80% H₂, 19% He, 1% CH₄",
      moons: 16,
      dayLength: "16.1 hours",
      yearLength: "164.8 years",
    },
    description:
      "Neptune is the solar system's outermost planet — a deep blue ice giant battered by supersonic winds. It reigns over the distant frontier of the planetary system, cold and dark but surprisingly dynamic.",
  },
];

export const sunData = {
  name: "Sun",
  radius: 695508,
  displayRadius: 4,
  color: "#FDB813",
  emissiveColor: "#ff8800",
  description:
    "The Sun is a G-type main-sequence star containing 99.86% of the mass of the entire solar system. Its core fuses 600 million tons of hydrogen into helium every second, producing the light and heat that make life on Earth possible.",
};
